### ISSUE TITLE
Error using dataloader on Ubuntu

### ISSUE THREAD

**Issue by SeanNaren** [NervanaSystems/aeon#39]
I'm running into an error on an AWS node (Ubuntu 14.04 p2.8xlarge, CUDA 8.0) after installing the `aeon` repo. I had to update my clang to 3.5 in order to run `python setup.py install` to completion. Here is the code I'm trying to run (which works fine on my local machine):

```
from aeon import DataLoader, gen_backend

audio_config = dict(sample_freq_hz=16000,
                    max_duration="%f seconds" % 6.4,
                    frame_length="%f seconds" % 0.02,
                    frame_stride="%f seconds" % 0.01,
                    window_type='hamming',
                    noise_index_file='noise_manifest.csv',
                    add_noise_probability=0.5,
                    noise_level=(0.5, 1)
                    )
alphabet = "_'ABCDEFGHIJKLMNOPQRSTUVWXYZ "

transcription_config = dict(alphabet=alphabet,
                            max_length=1300,
                            pack_for_ctc=True)
train_dataloader_config = dict(type="audio,transcription",
                               audio=audio_config,
                               transcription=transcription_config,
                               manifest_filename='train_manifest.csv',
                               macrobatch_size=1,
                               minibatch_size=1)
be = gen_backend()
train_loader = DataLoader(train_dataloader_config, be)
train_loader.next()
```

And here is the error:
```
Traceback (most recent call last):
  File "main.py", line 213, in <module>
    main()
  File "main.py", line 92, in main
    train_loader = DataLoader(train_dataloader_config, be)
  File "/home/sean.narenthiran/anaconda2/lib/python2.7/site-packages/aeon/dataloader.py", line 56, in __init__
    self._load_library()
  File "/home/sean.narenthiran/anaconda2/lib/python2.7/site-packages/aeon/dataloader.py", line 83, in _load_library
    self.loaderlib = ct.cdll.LoadLibrary(libpath)
  File "/home/sean.narenthiran/anaconda2/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/home/sean.narenthiran/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sean.narenthiran/anaconda2/lib/python2.7/site-packages/aeon_lib.so: undefined symbol: _ZNSt13runtime_errorC1EPKc
```

This is also on an Anaconda 2.7 install for linux. Thanks for making this library available :)

**Comment by SeanNaren** [comment]
This is not an easy bug to fix, and is to do with your clang version/gcc/++ version. 

It isn't very clear as to what install instruction works correctly but I'd suggest making sure you use the gcc/++ that is installed system wide (doing a `which gcc` should return something like `usr/bin/gcc`). I was following this up with the pytorch install which installs its own version of gcc in anaconda which may have been causing the issue...
