### ISSUE TITLE
seg fault when running cifar10 resnet example

### ISSUE THREAD

**Issue by marcel-n** [NervanaSystems/aeon#43]
Segmentation fault when running the cifar10_msra training example on a small ResNet.

```bash
python examples/cifar10_msra/train.py --depth 1 -b gpu -i 1 -o resnet1-f32 -d f32 --subset_pct 10 -e 1
autoflex config: {'bit_buffer': 1, 'num_std': 3, 'stale_threshold': 1200000, 'stats_queue_len': 16, 'offset': 100}
Epoch 0   [Train |████████████████████|   79/79   batches, 1.80 cost, 11.55s] [CrossEntropyMulti Loss 1.73, 0.53s]
Segmentation fault (core dumped)
```

gdb output suggests it might be related to the block_loader_file::fetch_block

```
#6  0x00007fffd4a249ee in nervana::block_loader_file::fetch_block (this=0x6a6ef48, block_num=<optimized out>) at loader/src/block_loader_file.cpp:106
#7  0x00007fffd4a25c17 in operator() (this=<optimized out>, __args=<optimized out>)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/functional:2471
#8  nervana::async::entry (this=0x6a6ef68, param=0x6eae178) at loader/src/util.hpp:182
#9  0x00007fffe06e3a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff7bc4184 in start_thread (arg=0x7fff8cff9700) at pthread_create.c:312
#11 0x00007ffff78f137d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by apark263** [comment]
should be fixed with latest release 0.2.7
